default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: market_place_api_development

test:
  <<: *default
  database: market_place_api_test

production:
  <<: *default
  database: market_place_api_production
